version: "3.8"
services:
  web:
    container_name: valent-excolator-jobs-go
    volumes:
      - ./app:/go/src/app
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: db
    depends_on:
      - db
    tty: true
  db:
    container_name: valent-excolator-jobs-db
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: valent_excolator_jobs
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql